% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={UniversalBank\_Naive Bayes},
  pdfauthor={Avinash Ravipudi},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{UniversalBank\_Naive Bayes}
\author{Avinash Ravipudi}
\date{2022-10-15}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(ggplot2)}
\FunctionTok{library}\NormalTok{(lattice)}
\FunctionTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(readr)}
\FunctionTok{library}\NormalTok{(caret)}
\FunctionTok{library}\NormalTok{(dplyr)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(e1071)}
\FunctionTok{library}\NormalTok{(class)}
\FunctionTok{library}\NormalTok{(ISLR)}
\end{Highlighting}
\end{Shaded}

\#Importing Data set

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#importing Data set and converting }
\FunctionTok{getwd}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "/Users/avinashravipudi/Desktop/FMLAssignment3"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{UB}\OtherTok{\textless{}{-}}\FunctionTok{read.csv}\NormalTok{(}\StringTok{"UniversalBank.csv"}\NormalTok{)}
\CommentTok{\#summarize the Data}
\FunctionTok{str}\NormalTok{(UB)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    5000 obs. of  14 variables:
##  $ ID                : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ Age               : int  25 45 39 35 35 37 53 50 35 34 ...
##  $ Experience        : int  1 19 15 9 8 13 27 24 10 9 ...
##  $ Income            : int  49 34 11 100 45 29 72 22 81 180 ...
##  $ ZIP.Code          : int  91107 90089 94720 94112 91330 92121 91711 93943 90089 93023 ...
##  $ Family            : int  4 3 1 1 4 4 2 1 3 1 ...
##  $ CCAvg             : num  1.6 1.5 1 2.7 1 0.4 1.5 0.3 0.6 8.9 ...
##  $ Education         : int  1 1 1 2 2 2 2 3 2 3 ...
##  $ Mortgage          : int  0 0 0 0 0 155 0 0 104 0 ...
##  $ Personal.Loan     : int  0 0 0 0 0 0 0 0 0 1 ...
##  $ Securities.Account: int  1 1 0 0 0 0 0 0 0 0 ...
##  $ CD.Account        : int  0 0 0 0 0 0 0 0 0 0 ...
##  $ Online            : int  0 0 0 0 0 1 1 0 1 0 ...
##  $ CreditCard        : int  0 0 0 0 1 0 0 1 0 0 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{head}\NormalTok{(UB)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   ID Age Experience Income ZIP.Code Family CCAvg Education Mortgage
## 1  1  25          1     49    91107      4   1.6         1        0
## 2  2  45         19     34    90089      3   1.5         1        0
## 3  3  39         15     11    94720      1   1.0         1        0
## 4  4  35          9    100    94112      1   2.7         2        0
## 5  5  35          8     45    91330      4   1.0         2        0
## 6  6  37         13     29    92121      4   0.4         2      155
##   Personal.Loan Securities.Account CD.Account Online CreditCard
## 1             0                  1          0      0          0
## 2             0                  1          0      0          0
## 3             0                  0          0      0          0
## 4             0                  0          0      0          0
## 5             0                  0          0      0          1
## 6             0                  0          0      1          0
\end{verbatim}

\#Checking for Missing Values

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{colMeans}\NormalTok{(}\FunctionTok{is.na}\NormalTok{(UB))  }
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                 ID                Age         Experience             Income 
##                  0                  0                  0                  0 
##           ZIP.Code             Family              CCAvg          Education 
##                  0                  0                  0                  0 
##           Mortgage      Personal.Loan Securities.Account         CD.Account 
##                  0                  0                  0                  0 
##             Online         CreditCard 
##                  0                  0
\end{verbatim}

\#Converting \& Summary online variables

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DF\_UB}\OtherTok{\textless{}{-}}\NormalTok{UB}\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{select}\NormalTok{(Age,Experience,Income,Family,CCAvg,Education,Mortgage,Personal.Loan,Securities.Account,CD.Account,Online,CreditCard)}

\NormalTok{DF\_UB}\SpecialCharTok{$}\NormalTok{CreditCard }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(DF\_UB}\SpecialCharTok{$}\NormalTok{CreditCard)}
\FunctionTok{summary}\NormalTok{(DF\_UB}\SpecialCharTok{$}\NormalTok{CreditCard)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    0    1 
## 3530 1470
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{is.factor}\NormalTok{(DF\_UB}\SpecialCharTok{$}\NormalTok{CreditCard)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DF\_UB}\SpecialCharTok{$}\NormalTok{Personal.Loan }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{((DF\_UB}\SpecialCharTok{$}\NormalTok{Personal.Loan))}
\FunctionTok{summary}\NormalTok{(DF\_UB}\SpecialCharTok{$}\NormalTok{Personal.Loan)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    0    1 
## 4520  480
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{is.factor}\NormalTok{(DF\_UB}\SpecialCharTok{$}\NormalTok{Personal.Loan)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{DF\_UB}\SpecialCharTok{$}\NormalTok{Online }\OtherTok{\textless{}{-}} \FunctionTok{as.factor}\NormalTok{(DF\_UB}\SpecialCharTok{$}\NormalTok{Online)}
\FunctionTok{summary}\NormalTok{(DF\_UB}\SpecialCharTok{$}\NormalTok{Online)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    0    1 
## 2016 2984
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{is.factor}\NormalTok{(DF\_UB}\SpecialCharTok{$}\NormalTok{Online)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\#split data 60\% Training and 40\% validation

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{selected.var }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{8}\NormalTok{,}\DecValTok{11}\NormalTok{,}\DecValTok{12}\NormalTok{)}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{1}\NormalTok{)}
\NormalTok{Train\_Index }\OtherTok{=} \FunctionTok{createDataPartition}\NormalTok{(DF\_UB}\SpecialCharTok{$}\NormalTok{Personal.Loan, }\AttributeTok{p=}\FloatTok{0.60}\NormalTok{, }\AttributeTok{list=}\ConstantTok{FALSE}\NormalTok{) }
\NormalTok{Train\_Data }\OtherTok{=}\NormalTok{ DF\_UB[Train\_Index,selected.var]}
\NormalTok{Validation\_Data }\OtherTok{=}\NormalTok{ DF\_UB[}\SpecialCharTok{{-}}\NormalTok{Train\_Index,selected.var]}
\end{Highlighting}
\end{Shaded}

\#A.Pivot Table for credit card, Loan \& Online

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{attach}\NormalTok{(Train\_Data)}
\FunctionTok{ftable}\NormalTok{(CreditCard,Personal.Loan,Online)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                          Online    0    1
## CreditCard Personal.Loan                 
## 0          0                     780 1126
##            1                      77  120
## 1          0                     303  503
##            1                      39   52
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{detach}\NormalTok{(Train\_Data)}
\end{Highlighting}
\end{Shaded}

The pivot table is now created with online as a column, Credit Card and
LOAN as rows.

\#B) (probability not using Naive Bayes) With Online=1 and Credit
Card=1, we can calculate the likelihood that Loan=1 by , we add
52(Loan=1 from ftable) and 503(Loan=0 from ftable) which gives us 555.
Probability= 52/555 = 0.09369 or 9.36\% . Hence the probability is
9.36\%

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{ftable}\NormalTok{(Train\_Data}\SpecialCharTok{$}\NormalTok{CreditCard,Train\_Data}\SpecialCharTok{$}\NormalTok{Online,Train\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan),}\AttributeTok{margin=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               0          1
##                           
## 0 0  0.91015169 0.08984831
##   1  0.90369181 0.09630819
## 1 0  0.88596491 0.11403509
##   1  0.90630631 0.09369369
\end{verbatim}

The above table shows chances of geting a loan if you have a credit card
and you apply online

\#C: pivot table between personal loan and online , personal loan \&
credit card

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{attach}\NormalTok{(Train\_Data)}
\FunctionTok{ftable}\NormalTok{(Personal.Loan,Online)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               Online    0    1
## Personal.Loan                 
## 0                    1083 1629
## 1                     116  172
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ftable}\NormalTok{(Personal.Loan,CreditCard)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               CreditCard    0    1
## Personal.Loan                     
## 0                        1906  806
## 1                         197   91
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{detach}\NormalTok{(Train\_Data)}
\end{Highlighting}
\end{Shaded}

The two pivot tables of above written as follows 1.In First pivot table:
Online as a column \& personal loan as row 2.In second Pivot table:
Credit card as column \& personal row as row

\#D Propotion Pivot table

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{ftable}\NormalTok{(Train\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan,Train\_Data}\SpecialCharTok{$}\NormalTok{CreditCard),}\AttributeTok{margin=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            0         1
##                       
## 0  0.7028024 0.2971976
## 1  0.6840278 0.3159722
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{prop.table}\NormalTok{(}\FunctionTok{ftable}\NormalTok{(Train\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan,Train\_Data}\SpecialCharTok{$}\NormalTok{Online),}\AttributeTok{margin=}\DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##            0         1
##                       
## 0  0.3993363 0.6006637
## 1  0.4027778 0.5972222
\end{verbatim}

The code above displays a proportion pivot table that can assist in
answering question D. D1) 91/288 = 0.3159 or 31.59\%\\
D2) 172/288 = 0.5972 or 59.72\% D3) total loans= 1 from table (288) is
now divided by total count from table (3000) = 0.096 or 9.6\% D4)
806/2712 = 0.2971 or 29.71\% D5) 1629/2712 = 0.6006 or 60.06\% D6) total
loans=0 from table(2712) which is divided by total count from table
(3000) = 0.904 or 90.4\%

\#E)Naive Bayes calculation (0.3159 * 0.5972 * 0.096)/{[}(0.3159 *
0.5972 * 0.096)+(0.2971 * 0.6006 * 0.904){]} = 0.0528913646 or 5.29\%

\#F) While E uses probability for each of the counts, B does a direct
computation based on a count. As a result, B is more exact, but E is
best for broad generality.

\#\#G)

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Universal.nb }\OtherTok{\textless{}{-}} \FunctionTok{naiveBayes}\NormalTok{(Personal.Loan }\SpecialCharTok{\textasciitilde{}}\NormalTok{ ., }\AttributeTok{data =}\NormalTok{ Train\_Data)}
\NormalTok{Universal.nb}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Naive Bayes Classifier for Discrete Predictors
## 
## Call:
## naiveBayes.default(x = X, y = Y, laplace = laplace)
## 
## A-priori probabilities:
## Y
##     0     1 
## 0.904 0.096 
## 
## Conditional probabilities:
##    Online
## Y           0         1
##   0 0.3993363 0.6006637
##   1 0.4027778 0.5972222
## 
##    CreditCard
## Y           0         1
##   0 0.7028024 0.2971976
##   1 0.6840278 0.3159722
\end{verbatim}

While understanding how you're computing P(LOAN=1\textbar CC=1,Online=1)
using the Naive Bayes model is made straightforward by utilizing the two
tables created in step C, you can also rapidly compute
P(LOAN=1\textbar CC=1,Online=1) using the pivot table created in step B.

Although it is less than that determined manually in step E, the
probability predicted by the Naive Bayes model is the same as that
projected by the prior techniques. This probability is closer to the one
discovered in step B. This might be the case since step E's calculations
are done manually, which leaves space for mistake when rounding
fractions and results in approximations.

\#NB confusion matrix for Train\_Data

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred.class }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(Universal.nb, }\AttributeTok{newdata =}\NormalTok{ Train\_Data)}
\FunctionTok{confusionMatrix}\NormalTok{(pred.class, Train\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    0    1
##          0 2712  288
##          1    0    0
##                                           
##                Accuracy : 0.904           
##                  95% CI : (0.8929, 0.9143)
##     No Information Rate : 0.904           
##     P-Value [Acc > NIR] : 0.5157          
##                                           
##                   Kappa : 0               
##                                           
##  Mcnemar's Test P-Value : <2e-16          
##                                           
##             Sensitivity : 1.000           
##             Specificity : 0.000           
##          Pos Pred Value : 0.904           
##          Neg Pred Value :   NaN           
##              Prevalence : 0.904           
##          Detection Rate : 0.904           
##    Detection Prevalence : 1.000           
##       Balanced Accuracy : 0.500           
##                                           
##        'Positive' Class : 0               
## 
\end{verbatim}

Despite being extremely sensitive, this model showed a low specificity.
Although the reference had all actual values, the model predicted that
all values would be zero. Due to the high amount of 0 values, the model
still provides a 90.4 percent accuracy even when all 1 data were absent.

\#\#Validation set

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pred.prob }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(Universal.nb, }\AttributeTok{newdata=}\NormalTok{Validation\_Data, }\AttributeTok{type=}\StringTok{"raw"}\NormalTok{)}
\NormalTok{pred.class }\OtherTok{\textless{}{-}} \FunctionTok{predict}\NormalTok{(Universal.nb, }\AttributeTok{newdata =}\NormalTok{ Validation\_Data)}
\FunctionTok{confusionMatrix}\NormalTok{(pred.class, Validation\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    0    1
##          0 1808  192
##          1    0    0
##                                           
##                Accuracy : 0.904           
##                  95% CI : (0.8902, 0.9166)
##     No Information Rate : 0.904           
##     P-Value [Acc > NIR] : 0.5192          
##                                           
##                   Kappa : 0               
##                                           
##  Mcnemar's Test P-Value : <2e-16          
##                                           
##             Sensitivity : 1.000           
##             Specificity : 0.000           
##          Pos Pred Value : 0.904           
##          Neg Pred Value :   NaN           
##              Prevalence : 0.904           
##          Detection Rate : 0.904           
##    Detection Prevalence : 1.000           
##       Balanced Accuracy : 0.500           
##                                           
##        'Positive' Class : 0               
## 
\end{verbatim}

Let's take a visual look at the model to determine what the optimal
threshold is for it.

\#ROC

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(pROC)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Type 'citation("pROC")' for a citation.
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'pROC'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     cov, smooth, var
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{roc}\NormalTok{(Validation\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan,pred.prob[,}\DecValTok{1}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Setting levels: control = 0, case = 1
\end{verbatim}

\begin{verbatim}
## Setting direction: controls < cases
\end{verbatim}

\begin{verbatim}
## 
## Call:
## roc.default(response = Validation_Data$Personal.Loan, predictor = pred.prob[,     1])
## 
## Data: pred.prob[, 1] in 1808 controls (Validation_Data$Personal.Loan 0) < 192 cases (Validation_Data$Personal.Loan 1).
## Area under the curve: 0.5193
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plot.roc}\NormalTok{(Validation\_Data}\SpecialCharTok{$}\NormalTok{Personal.Loan,pred.prob[,}\DecValTok{1}\NormalTok{],}\AttributeTok{print.thres=}\StringTok{"best"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Setting levels: control = 0, case = 1
## Setting direction: controls < cases
\end{verbatim}

\includegraphics{UniversalBank_Naive-Bayes_files/figure-latex/unnamed-chunk-13-1.pdf}
Setting a threshold of 0.906 improves the model by decreasing
sensitivity to 0.464 and improving specificity to 0.576. ```

\end{document}
